# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(1128, 629)
        HelpWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(HelpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 1131, 241))
        self.frame_11.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(28, 113, 216);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label18 = QtWidgets.QLabel(self.frame_11)
        self.label18.setGeometry(QtCore.QRect(430, 10, 221, 71))
        self.label18.setStyleSheet("font: 63 italic 40pt \"URW Bookman\";\n"
"color:white;")
        self.label18.setObjectName("label18")
        self.icon8 = QtWidgets.QPushButton(self.frame_11)
        self.icon8.setGeometry(QtCore.QRect(560, 10, 89, 41))
        self.icon8.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon8.setIcon(icon)
        self.icon8.setIconSize(QtCore.QSize(50, 50))
        self.icon8.setObjectName("icon8")
        self.help_backbtn = QtWidgets.QPushButton(self.frame_11)
        self.help_backbtn.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.help_backbtn.setStyleSheet("")
        self.help_backbtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_backbtn.setIcon(icon1)
        self.help_backbtn.setIconSize(QtCore.QSize(40, 40))
        self.help_backbtn.setObjectName("help_backbtn")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setGeometry(QtCore.QRect(390, 80, 291, 451))
        self.frame_12.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgba(42, 41, 41, 0)")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.icon10 = QtWidgets.QPushButton(self.frame_12)
        self.icon10.setGeometry(QtCore.QRect(-10, 0, 311, 451))
        self.icon10.setStyleSheet("")
        self.icon10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/hand-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon10.setIcon(icon2)
        self.icon10.setIconSize(QtCore.QSize(450, 450))
        self.icon10.setObjectName("icon10")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setGeometry(QtCore.QRect(29, 29, 241, 401))
        self.frame_13.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.icon9 = QtWidgets.QPushButton(self.frame_12)
        self.icon9.setGeometry(QtCore.QRect(110, 70, 71, 51))
        self.icon9.setStyleSheet("")
        self.icon9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/lifesaver (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon9.setIcon(icon3)
        self.icon9.setIconSize(QtCore.QSize(50, 50))
        self.icon9.setObjectName("icon9")
        self.help_codebtn = QtWidgets.QPushButton(self.frame_12)
        self.help_codebtn.setGeometry(QtCore.QRect(50, 150, 191, 51))
        self.help_codebtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(28, 113, 216);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/coding.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_codebtn.setIcon(icon4)
        self.help_codebtn.setIconSize(QtCore.QSize(30, 30))
        self.help_codebtn.setObjectName("help_codebtn")
        self.help_tutorialbtn = QtWidgets.QPushButton(self.frame_12)
        self.help_tutorialbtn.setGeometry(QtCore.QRect(50, 210, 191, 51))
        self.help_tutorialbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(28, 113, 216);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/video-tutorials.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_tutorialbtn.setIcon(icon5)
        self.help_tutorialbtn.setIconSize(QtCore.QSize(30, 30))
        self.help_tutorialbtn.setObjectName("help_tutorialbtn")
        self.help_bugbtn = QtWidgets.QPushButton(self.frame_12)
        self.help_bugbtn.setGeometry(QtCore.QRect(50, 270, 191, 51))
        self.help_bugbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(28, 113, 216);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/bug-report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_bugbtn.setIcon(icon6)
        self.help_bugbtn.setIconSize(QtCore.QSize(30, 30))
        self.help_bugbtn.setObjectName("help_bugbtn")
        self.help_contactbtn = QtWidgets.QPushButton(self.frame_12)
        self.help_contactbtn.setGeometry(QtCore.QRect(50, 330, 191, 51))
        self.help_contactbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(28, 113, 216);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/contact-us.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_contactbtn.setIcon(icon7)
        self.help_contactbtn.setIconSize(QtCore.QSize(30, 30))
        self.help_contactbtn.setObjectName("help_contactbtn")
        self.frame_13.raise_()
        self.icon10.raise_()
        self.icon9.raise_()
        self.help_codebtn.raise_()
        self.help_tutorialbtn.raise_()
        self.help_bugbtn.raise_()
        self.help_contactbtn.raise_()
        # HelpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HelpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        # HelpWindow.setMenuBar(self.menubar)

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "Help"))
        self.label18.setText(_translate("HelpWindow", "Library"))
        self.help_codebtn.setText(_translate("HelpWindow", "Check the code"))
        self.help_tutorialbtn.setText(_translate("HelpWindow", "Tutorial"))
        self.help_bugbtn.setText(_translate("HelpWindow", "Report a bug"))
        self.help_contactbtn.setText(_translate("HelpWindow", "Contact Us"))
