# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyaccWindow(object):
    def setupUi(self, MyaccWindow):
        MyaccWindow.setObjectName("MyaccWindow")
        MyaccWindow.resize(1128, 629)
        MyaccWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(MyaccWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(180, 130, 401, 471))
        self.frame_10.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label29 = QtWidgets.QLabel(self.frame_10)
        self.label29.setGeometry(QtCore.QRect(40, 220, 181, 31))
        self.label29.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label29.setObjectName("label29")
        self.label26 = QtWidgets.QLabel(self.frame_10)
        self.label26.setGeometry(QtCore.QRect(60, 10, 271, 71))
        self.label26.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label26.setObjectName("label26")
        self.label28 = QtWidgets.QLabel(self.frame_10)
        self.label28.setGeometry(QtCore.QRect(40, 150, 151, 31))
        self.label28.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label28.setObjectName("label28")
        self.SUBMIT = QtWidgets.QPushButton(self.frame_10)
        self.SUBMIT.setGeometry(QtCore.QRect(90, 340, 191, 41))
        self.SUBMIT.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.SUBMIT.setIconSize(QtCore.QSize(30, 30))
        self.SUBMIT.setObjectName("SUBMIT")
        self.label27 = QtWidgets.QLabel(self.frame_10)
        self.label27.setGeometry(QtCore.QRect(40, 80, 161, 31))
        self.label27.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label27.setObjectName("label27")
        self.CURRENT_PASSWORD = QtWidgets.QLineEdit(self.frame_10)
        self.CURRENT_PASSWORD.setGeometry(QtCore.QRect(40, 110, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.CURRENT_PASSWORD.setFont(font)
        self.CURRENT_PASSWORD.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.CURRENT_PASSWORD.setMaxLength(2000)
        self.CURRENT_PASSWORD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.CURRENT_PASSWORD.setDragEnabled(True)
        self.CURRENT_PASSWORD.setPlaceholderText("")
        self.CURRENT_PASSWORD.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.CURRENT_PASSWORD.setClearButtonEnabled(True)
        self.CURRENT_PASSWORD.setObjectName("CURRENT_PASSWORD")
        self.NEW_PASSWORD = QtWidgets.QLineEdit(self.frame_10)
        self.NEW_PASSWORD.setGeometry(QtCore.QRect(40, 180, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.NEW_PASSWORD.setFont(font)
        self.NEW_PASSWORD.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.NEW_PASSWORD.setMaxLength(2000)
        self.NEW_PASSWORD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.NEW_PASSWORD.setDragEnabled(True)
        self.NEW_PASSWORD.setPlaceholderText("")
        self.NEW_PASSWORD.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.NEW_PASSWORD.setClearButtonEnabled(True)
        self.NEW_PASSWORD.setObjectName("NEW_PASSWORD")
        self.CONFIRME_PASSWORD = QtWidgets.QLineEdit(self.frame_10)
        self.CONFIRME_PASSWORD.setGeometry(QtCore.QRect(40, 250, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.CONFIRME_PASSWORD.setFont(font)
        self.CONFIRME_PASSWORD.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.CONFIRME_PASSWORD.setMaxLength(2000)
        self.CONFIRME_PASSWORD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.CONFIRME_PASSWORD.setDragEnabled(True)
        self.CONFIRME_PASSWORD.setPlaceholderText("")
        self.CONFIRME_PASSWORD.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.CONFIRME_PASSWORD.setClearButtonEnabled(True)
        self.CONFIRME_PASSWORD.setObjectName("CONFIRME_PASSWORD")
        self.DISPLAY = QtWidgets.QLabel(self.frame_10)
        self.DISPLAY.setGeometry(QtCore.QRect(30, 310, 321, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.DISPLAY.setFont(font)
        self.DISPLAY.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgba(42, 41, 41, 0);")
        self.DISPLAY.setText("")
        self.DISPLAY.setTextFormat(QtCore.Qt.AutoText)
        self.DISPLAY.setAlignment(QtCore.Qt.AlignCenter)
        self.DISPLAY.setWordWrap(False)
        self.DISPLAY.setObjectName("DISPLAY")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 171, 621))
        self.frame_16.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label19 = QtWidgets.QLabel(self.frame_16)
        self.label19.setGeometry(QtCore.QRect(10, 0, 141, 71))
        self.label19.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label19.setObjectName("label19")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 101, 41))
        self.pushButton_14.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.pushButton_14.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Library Management/Icons/graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.log_credits_24 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_24.setGeometry(QtCore.QRect(920, 20, 181, 41))
        self.log_credits_24.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Library Management/Icons/programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_24.setIcon(icon1)
        self.log_credits_24.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_24.setObjectName("log_credits_24")
        self.log_credits_25 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_25.setGeometry(QtCore.QRect(920, 70, 181, 41))
        self.log_credits_25.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Library Management/Icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_25.setIcon(icon2)
        self.log_credits_25.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_25.setObjectName("log_credits_25")
        self.MY_ACCOUNT = QtWidgets.QPushButton(self.frame_16)
        self.MY_ACCOUNT.setGeometry(QtCore.QRect(10, 180, 151, 51))
        self.MY_ACCOUNT.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.MY_ACCOUNT.setIcon(icon1)
        self.MY_ACCOUNT.setIconSize(QtCore.QSize(25, 25))
        self.MY_ACCOUNT.setObjectName("MY_ACCOUNT")
        self.BOOKS = QtWidgets.QPushButton(self.frame_16)
        self.BOOKS.setGeometry(QtCore.QRect(10, 240, 151, 51))
        self.BOOKS.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.BOOKS.setIcon(icon2)
        self.BOOKS.setIconSize(QtCore.QSize(25, 25))
        self.BOOKS.setObjectName("BOOKS")
        self.REQUEST = QtWidgets.QPushButton(self.frame_16)
        self.ABOUT_US = QtWidgets.QPushButton(self.frame_16)
        self.REQUEST.setGeometry(QtCore.QRect(10, 300, 151, 51))
        self.ABOUT_US.setGeometry(QtCore.QRect(10, 530, 151, 51))
        self.REQUEST.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")     
        self.ABOUT_US.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:transparent;\n"
"    border: 0px solid white;\n"
"    border-radius: 0px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 16px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: transparent;;\n"
"}\n"
"")    
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Library Management/Icons/interview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.REQUEST.setIcon(icon3)
        self.REQUEST.setIconSize(QtCore.QSize(25, 25))
        self.REQUEST.setObjectName("REQUEST")
        self.ABOUT_US.setObjectName("ABOUT_US")
        self.icon11 = QtWidgets.QPushButton(self.frame_16)
        self.icon11.setGeometry(QtCore.QRect(-20, 50, 191, 111))
        self.icon11.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon11.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Library Management/Icons/digital-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon11.setIcon(icon4)
        self.icon11.setIconSize(QtCore.QSize(100, 100))
        self.icon11.setObjectName("icon11")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(590, 130, 531, 471))
        self.frame_9.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label32 = QtWidgets.QLabel(self.frame_9)
        self.label32.setGeometry(QtCore.QRect(260, 120, 101, 31))
        self.label32.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label32.setObjectName("label32")
        self.label33 = QtWidgets.QLabel(self.frame_9)
        self.label33.setGeometry(QtCore.QRect(50, 190, 21, 31))
        self.label33.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label33.setObjectName("label33")
        self.label34 = QtWidgets.QLabel(self.frame_9)
        self.label34.setGeometry(QtCore.QRect(260, 190, 121, 31))
        self.label34.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label34.setObjectName("label34")
        self.label35 = QtWidgets.QLabel(self.frame_9)
        self.label35.setGeometry(QtCore.QRect(190, 270, 131, 31))
        self.label35.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label35.setObjectName("label35")
        self.label30 = QtWidgets.QLabel(self.frame_9)
        self.label30.setGeometry(QtCore.QRect(80, 10, 271, 71))
        self.label30.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label30.setObjectName("label30")
        self.label31 = QtWidgets.QLabel(self.frame_9)
        self.label31.setGeometry(QtCore.QRect(50, 120, 151, 31))
        self.label31.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label31.setObjectName("label31")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_11.setGeometry(QtCore.QRect(260, 220, 61, 31))
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet("background-color: white;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"background-color: rgba(42, 41, 41, 0);\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Library Management/Icons/algeria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.icon13 = QtWidgets.QPushButton(self.frame_9)
        self.icon13.setGeometry(QtCore.QRect(330, 10, 111, 51))
        self.icon13.setStyleSheet("")
        self.icon13.setText("")
        self.icon13.setIcon(icon1)
        self.icon13.setIconSize(QtCore.QSize(50, 50))
        self.icon13.setObjectName("icon13")
        self.FIRST_NAME = QtWidgets.QLineEdit(self.frame_9)
        self.FIRST_NAME.setGeometry(QtCore.QRect(50, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.FIRST_NAME.setFont(font)
        self.FIRST_NAME.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.FIRST_NAME.setMaxLength(100)
        self.FIRST_NAME.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.FIRST_NAME.setDragEnabled(True)
        self.FIRST_NAME.setReadOnly(True)
        self.FIRST_NAME.setPlaceholderText("")
        self.FIRST_NAME.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.FIRST_NAME.setClearButtonEnabled(False)
        self.FIRST_NAME.setObjectName("FIRST_NAME")
        self.LAST_NAME = QtWidgets.QLineEdit(self.frame_9)
        self.LAST_NAME.setGeometry(QtCore.QRect(260, 150, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.LAST_NAME.setFont(font)
        self.LAST_NAME.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.LAST_NAME.setMaxLength(100)
        self.LAST_NAME.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LAST_NAME.setDragEnabled(True)
        self.LAST_NAME.setReadOnly(True)
        self.LAST_NAME.setPlaceholderText("")
        self.LAST_NAME.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.LAST_NAME.setClearButtonEnabled(False)
        self.LAST_NAME.setObjectName("LAST_NAME")
        self.ID = QtWidgets.QLineEdit(self.frame_9)
        self.ID.setGeometry(QtCore.QRect(50, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ID.setFont(font)
        self.ID.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.ID.setMaxLength(100)
        self.ID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ID.setDragEnabled(True)
        self.ID.setReadOnly(True)
        self.ID.setPlaceholderText("")
        self.ID.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ID.setClearButtonEnabled(False)
        self.ID.setObjectName("ID")
        self.PHONE = QtWidgets.QLineEdit(self.frame_9)
        self.PHONE.setGeometry(QtCore.QRect(320, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.PHONE.setFont(font)
        self.PHONE.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.PHONE.setMaxLength(100)
        self.PHONE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PHONE.setDragEnabled(True)
        self.PHONE.setReadOnly(True)
        self.PHONE.setPlaceholderText("")
        self.PHONE.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.PHONE.setClearButtonEnabled(False)
        self.PHONE.setObjectName("PHONE")
        self.EMAIL_ADDRESS = QtWidgets.QLineEdit(self.frame_9)
        self.EMAIL_ADDRESS.setGeometry(QtCore.QRect(150, 300, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.EMAIL_ADDRESS.setFont(font)
        self.EMAIL_ADDRESS.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.EMAIL_ADDRESS.setMaxLength(100)
        self.EMAIL_ADDRESS.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.EMAIL_ADDRESS.setDragEnabled(True)
        self.EMAIL_ADDRESS.setReadOnly(True)
        self.EMAIL_ADDRESS.setPlaceholderText("")
        self.EMAIL_ADDRESS.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.EMAIL_ADDRESS.setClearButtonEnabled(False)
        self.EMAIL_ADDRESS.setObjectName("EMAIL_ADDRESS")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(180, 0, 941, 121))
        self.frame_8.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label25 = QtWidgets.QLabel(self.frame_8)
        self.label25.setGeometry(QtCore.QRect(310, 20, 231, 71))
        self.label25.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label25.setObjectName("label25")
        self.LOGOUT = QtWidgets.QPushButton(self.frame_8)
        self.LOGOUT.setGeometry(QtCore.QRect(810, 10, 121, 41))
        self.LOGOUT.setStyleSheet("\n"
"QPushButton {\n"
"background-color:rgb(224, 27, 36);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Library Management/Icons/logout (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LOGOUT.setIcon(icon6)
        self.LOGOUT.setIconSize(QtCore.QSize(20, 20))
        self.LOGOUT.setObjectName("LOGOUT")
        #MyaccWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyaccWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        #MyaccWindow.setMenuBar(self.menubar)

        self.retranslateUi(MyaccWindow)
        QtCore.QMetaObject.connectSlotsByName(MyaccWindow)

    def retranslateUi(self, MyaccWindow):
        _translate = QtCore.QCoreApplication.translate
        MyaccWindow.setWindowTitle(_translate("MyaccWindow", "My Account"))
        self.label29.setText(_translate("MyaccWindow", "Confirme password"))
        self.label26.setText(_translate("MyaccWindow", "Change password"))
        self.label28.setText(_translate("MyaccWindow", "New password"))
        self.SUBMIT.setText(_translate("MyaccWindow", "Submit"))
        self.label27.setText(_translate("MyaccWindow", "Current password"))
        self.label19.setText(_translate("MyaccWindow", "Library"))
        self.log_credits_24.setText(_translate("MyaccWindow", "My account"))
        self.log_credits_25.setText(_translate("MyaccWindow", "Books"))
        self.MY_ACCOUNT.setText(_translate("MyaccWindow", "My account"))
        self.BOOKS.setText(_translate("MyaccWindow", "Books"))
        self.REQUEST.setText(_translate("MyaccWindow", "Request"))
        self.ABOUT_US.setText(_translate("MyaccWindow", "ABOUT US"))
        self.label32.setText(_translate("MyaccWindow", "Last Name"))
        self.label33.setText(_translate("MyaccWindow", "ID"))
        self.label34.setText(_translate("MyaccWindow", "Phone"))
        self.label35.setText(_translate("MyaccWindow", "Email Address"))
        self.label30.setText(_translate("MyaccWindow", "My Information"))
        self.label31.setText(_translate("MyaccWindow", "First name"))
        self.pushButton_11.setText(_translate("MyaccWindow", "+213"))
        self.label25.setText(_translate("MyaccWindow", "My Account"))
        self.LOGOUT.setText(_translate("MyaccWindow", "Logout"))
