# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Path import *

class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        self.path = path()
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(1128, 615)
        RegisterWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1131, 321))
        self.frame_3.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(28, 113, 216);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label8 = QtWidgets.QLabel(self.frame_3)
        self.label8.setGeometry(QtCore.QRect(160, 60, 221, 71))
        self.label8.setStyleSheet("font: 63 italic 40pt \"URW Bookman\";\n"
"color:white;")
        self.label8.setObjectName("label8")
        self.ABOUT = QtWidgets.QPushButton(self.frame_3)
        self.ABOUT.setGeometry(QtCore.QRect(170, 270, 171, 41))
        self.ABOUT.setStyleSheet("\n"
"QPushButton {\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    border:3px solid white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    background-color : transparent;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.ABOUT.setObjectName("ABOUT")
        self.icon4 = QtWidgets.QPushButton(self.frame_3)
        self.icon4.setGeometry(QtCore.QRect(290, 60, 89, 41))
        self.icon4.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.path+"graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon4.setIcon(icon)
        self.icon4.setIconSize(QtCore.QSize(50, 50))
        self.icon4.setObjectName("icon4")
        self.icon5 = QtWidgets.QPushButton(self.frame_3)
        self.icon5.setGeometry(QtCore.QRect(160, 130, 191, 111))
        self.icon5.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.path+"online-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon5.setIcon(icon1)
        self.icon5.setIconSize(QtCore.QSize(100, 100))
        self.icon5.setObjectName("icon5")
        self.BACK = QtWidgets.QPushButton(self.frame_3)
        self.BACK.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.BACK.setStyleSheet("")
        self.BACK.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.path+"previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BACK.setIcon(icon2)
        self.BACK.setIconSize(QtCore.QSize(40, 40))
        self.BACK.setObjectName("BACK")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(540, 20, 521, 561))
        self.frame_4.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label12 = QtWidgets.QLabel(self.frame_4)
        self.label12.setGeometry(QtCore.QRect(40, 130, 121, 31))
        self.label12.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label12.setObjectName("label12")
        self.label15 = QtWidgets.QLabel(self.frame_4)
        self.label15.setGeometry(QtCore.QRect(260, 210, 101, 20))
        self.label15.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label15.setObjectName("label15")
        self.SIGN_UP = QtWidgets.QPushButton(self.frame_4)
        self.SIGN_UP.setGeometry(QtCore.QRect(140, 450, 261, 41))
        self.SIGN_UP.setStyleSheet("\n"
"QPushButton {\n"
"    transition: all .5s ease;\n"
"    color: rgb(0, 137, 236);;\n"
"    border-radius: 5px;\n"
"    border:3px solid rgb(0, 137, 236);;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    background-color : transparent;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(0, 137, 236);;\n"
"}\n"
"")
        self.SIGN_UP.setObjectName("SIGN_UP")
        self.label11 = QtWidgets.QLabel(self.frame_4)
        self.label11.setGeometry(QtCore.QRect(280, 0, 151, 41))
        self.label11.setStyleSheet("font: 75 20pt \"Ubuntu\";")
        self.label11.setObjectName("label11")
        self.label10 = QtWidgets.QLabel(self.frame_4)
        self.label10.setGeometry(QtCore.QRect(190, 0, 91, 41))
        self.label10.setStyleSheet("font: 75 20pt \"Ubuntu\";\n"
"color:rgb(28, 113, 216);")
        self.label10.setObjectName("label10")
        self.label9 = QtWidgets.QLabel(self.frame_4)
        self.label9.setGeometry(QtCore.QRect(80, 0, 101, 41))
        self.label9.setStyleSheet("font: 75 20pt \"Ubuntu\";")
        self.label9.setObjectName("label9")
        self.icon6 = QtWidgets.QPushButton(self.frame_4)
        self.icon6.setGeometry(QtCore.QRect(180, 40, 111, 101))
        self.icon6.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.path+"add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon6.setIcon(icon3)
        self.icon6.setIconSize(QtCore.QSize(70, 70))
        self.icon6.setObjectName("icon6")
        self.label13 = QtWidgets.QLabel(self.frame_4)
        self.label13.setGeometry(QtCore.QRect(260, 140, 111, 17))
        self.label13.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label13.setObjectName("label13")
        self.label14 = QtWidgets.QLabel(self.frame_4)
        self.label14.setGeometry(QtCore.QRect(40, 210, 131, 20))
        self.label14.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label14.setObjectName("label14")
        self.label17 = QtWidgets.QLabel(self.frame_4)
        self.label17.setGeometry(QtCore.QRect(40, 350, 181, 20))
        self.label17.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label17.setObjectName("label17")
        self.label16 = QtWidgets.QLabel(self.frame_4)
        self.label16.setGeometry(QtCore.QRect(40, 280, 101, 20))
        self.label16.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label16.setObjectName("label16")
        self.icon7 = QtWidgets.QPushButton(self.frame_4)
        self.icon7.setGeometry(QtCore.QRect(260, 300, 61, 31))
        self.icon7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.icon7.setStyleSheet("background-color: rgba(42, 41, 41, 0);\n"
"\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.path+"algeria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon7.setIcon(icon4)
        self.icon7.setObjectName("icon7")
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setGeometry(QtCore.QRect(40, 420, 92, 23))
        self.checkBox.setObjectName("checkBox")
        self.re_error = QtWidgets.QLabel(self.frame_4)
        self.re_error.setGeometry(QtCore.QRect(40, 500, 451, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.re_error.setFont(font)
        self.re_error.setStyleSheet("color: rgb(224, 27, 36);")
        self.re_error.setText("")
        self.re_error.setTextFormat(QtCore.Qt.AutoText)
        self.re_error.setAlignment(QtCore.Qt.AlignCenter)
        self.re_error.setWordWrap(False)
        self.re_error.setObjectName("re_error")
        self.LAST_NAME = QtWidgets.QLineEdit(self.frame_4)
        self.LAST_NAME.setGeometry(QtCore.QRect(260, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.LAST_NAME.setFont(font)
        self.LAST_NAME.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.LAST_NAME.setMaxLength(100)
        self.LAST_NAME.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LAST_NAME.setDragEnabled(True)
        self.LAST_NAME.setPlaceholderText("")
        self.LAST_NAME.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.LAST_NAME.setClearButtonEnabled(True)
        self.LAST_NAME.setObjectName("LAST_NAME")
        self.EMAIL_ADDRESS = QtWidgets.QLineEdit(self.frame_4)
        self.EMAIL_ADDRESS.setGeometry(QtCore.QRect(40, 230, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.EMAIL_ADDRESS.setFont(font)
        self.EMAIL_ADDRESS.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.EMAIL_ADDRESS.setMaxLength(100)
        self.EMAIL_ADDRESS.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.EMAIL_ADDRESS.setDragEnabled(True)
        self.EMAIL_ADDRESS.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.EMAIL_ADDRESS.setClearButtonEnabled(True)
        self.EMAIL_ADDRESS.setObjectName("EMAIL_ADDRESS")
        self.ID = QtWidgets.QLineEdit(self.frame_4)
        self.ID.setGeometry(QtCore.QRect(260, 230, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ID.setFont(font)
        self.ID.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.ID.setMaxLength(10)
        self.ID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ID.setDragEnabled(True)
        self.ID.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ID.setClearButtonEnabled(True)
        self.ID.setObjectName("ID")
        self.PASSWORD = QtWidgets.QLineEdit(self.frame_4)
        self.PASSWORD.setGeometry(QtCore.QRect(40, 300, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.PASSWORD.setFont(font)
        self.PASSWORD.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.PASSWORD.setMaxLength(2000)
        self.PASSWORD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PASSWORD.setDragEnabled(True)
        self.PASSWORD.setPlaceholderText("")
        self.PASSWORD.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.PASSWORD.setClearButtonEnabled(True)
        self.PASSWORD.setObjectName("PASSWORD")
        self.CONFIRME_PASSWORD = QtWidgets.QLineEdit(self.frame_4)
        self.CONFIRME_PASSWORD.setGeometry(QtCore.QRect(40, 370, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.CONFIRME_PASSWORD.setFont(font)
        self.CONFIRME_PASSWORD.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.CONFIRME_PASSWORD.setMaxLength(2000)
        self.CONFIRME_PASSWORD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.CONFIRME_PASSWORD.setDragEnabled(True)
        self.CONFIRME_PASSWORD.setPlaceholderText("")
        self.CONFIRME_PASSWORD.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.CONFIRME_PASSWORD.setClearButtonEnabled(True)
        self.CONFIRME_PASSWORD.setObjectName("CONFIRME_PASSWORD")
        self.PHONE = QtWidgets.QLineEdit(self.frame_4)
        self.PHONE.setGeometry(QtCore.QRect(320, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.PHONE.setFont(font)
        self.PHONE.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.PHONE.setMaxLength(10)
        self.PHONE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PHONE.setDragEnabled(True)
        self.PHONE.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.PHONE.setClearButtonEnabled(True)
        self.PHONE.setObjectName("PHONE")
        self.label16_2 = QtWidgets.QLabel(self.frame_4)
        self.label16_2.setGeometry(QtCore.QRect(260, 280, 101, 20))
        self.label16_2.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label16_2.setObjectName("label16_2")
        self.FIRST_NAME = QtWidgets.QLineEdit(self.centralwidget)
        self.FIRST_NAME.setGeometry(QtCore.QRect(580, 180, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.FIRST_NAME.setFont(font)
        self.FIRST_NAME.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.FIRST_NAME.setMaxLength(100)
        self.FIRST_NAME.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.FIRST_NAME.setDragEnabled(True)
        self.FIRST_NAME.setPlaceholderText("")
        self.FIRST_NAME.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.FIRST_NAME.setClearButtonEnabled(True)
        self.FIRST_NAME.setObjectName("FIRST_NAME")
        #RegisterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegisterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        #RegisterWindow.setMenuBar(self.menubar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Register"))
        self.label8.setText(_translate("RegisterWindow", "Library"))
        self.ABOUT.setText(_translate("RegisterWindow", "ABOUT"))
        self.label12.setText(_translate("RegisterWindow", "First Name"))
        self.label15.setText(_translate("RegisterWindow", "ID"))
        self.SIGN_UP.setText(_translate("RegisterWindow", "Sign Up"))
        self.label11.setText(_translate("RegisterWindow", "membership"))
        self.label10.setText(_translate("RegisterWindow", "Library"))
        self.label9.setText(_translate("RegisterWindow", "Create a"))
        self.label13.setText(_translate("RegisterWindow", "Last Name"))
        self.label14.setText(_translate("RegisterWindow", "Email address"))
        self.label17.setText(_translate("RegisterWindow", "Confirme password"))
        self.label16.setText(_translate("RegisterWindow", "Password"))
        self.icon7.setText(_translate("RegisterWindow", "+213"))
        self.checkBox.setText(_translate("RegisterWindow", "I am sure "))
        self.EMAIL_ADDRESS.setPlaceholderText(_translate("RegisterWindow", "Someone@mail.com"))
        self.ID.setPlaceholderText(_translate("RegisterWindow", "193800...."))
        self.PHONE.setPlaceholderText(_translate("RegisterWindow", "612345678"))
        self.label16_2.setText(_translate("RegisterWindow", "Phone"))
