# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Request.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Path import path

class Ui_RequestWindow(object):
    def setupUi(self, RequestWindow):
        self.path = path()
        RequestWindow.setObjectName("RequestWindow")
        RequestWindow.resize(1128, 629)
        RequestWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(RequestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 171, 621))
        self.frame_16.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label19 = QtWidgets.QLabel(self.frame_16)
        self.label19.setGeometry(QtCore.QRect(10, 0, 141, 71))
        self.label19.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label19.setObjectName("label19")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 101, 41))
        self.pushButton_14.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.pushButton_14.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.path+"graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.log_credits_24 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_24.setGeometry(QtCore.QRect(920, 20, 181, 41))
        self.log_credits_24.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.path+"programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_24.setIcon(icon1)
        self.log_credits_24.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_24.setObjectName("log_credits_24")
        self.log_credits_25 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_25.setGeometry(QtCore.QRect(920, 70, 181, 41))
        self.log_credits_25.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.path+"book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_25.setIcon(icon2)
        self.log_credits_25.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_25.setObjectName("log_credits_25")
        self.MY_ACCOUNT = QtWidgets.QPushButton(self.frame_16)
        self.MY_ACCOUNT.setGeometry(QtCore.QRect(10, 180, 151, 51))
        self.MY_ACCOUNT.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.MY_ACCOUNT.setIcon(icon1)
        self.MY_ACCOUNT.setIconSize(QtCore.QSize(25, 25))
        self.MY_ACCOUNT.setObjectName("MY_ACCOUNT")
        self.BOOKS = QtWidgets.QPushButton(self.frame_16)
        self.BOOKS.setGeometry(QtCore.QRect(10, 240, 151, 51))
        self.BOOKS.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.BOOKS.setIcon(icon2)
        self.BOOKS.setIconSize(QtCore.QSize(25, 25))
        self.BOOKS.setObjectName("BOOKS")
        self.icon11 = QtWidgets.QPushButton(self.frame_16)
        self.icon11.setGeometry(QtCore.QRect(-20, 50, 191, 111))
        self.icon11.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon11.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.path+"digital-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon11.setIcon(icon3)
        self.icon11.setIconSize(QtCore.QSize(100, 100))
        self.icon11.setObjectName("icon11")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setGeometry(QtCore.QRect(390, 20, 511, 491))
        self.frame_15.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label38 = QtWidgets.QLabel(self.frame_15)
        self.label38.setGeometry(QtCore.QRect(90, 120, 91, 31))
        self.label38.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label38.setObjectName("label38")
        self.label39 = QtWidgets.QLabel(self.frame_15)
        self.label39.setGeometry(QtCore.QRect(90, 190, 91, 31))
        self.label39.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label39.setObjectName("label39")
        self.label40 = QtWidgets.QLabel(self.frame_15)
        self.label40.setGeometry(QtCore.QRect(90, 260, 121, 31))
        self.label40.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label40.setObjectName("label40")
        self.REQUEST = QtWidgets.QPushButton(self.frame_15)
        self.REQUEST.setGeometry(QtCore.QRect(130, 360, 261, 41))
        self.REQUEST.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.path+"interview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.REQUEST.setIcon(icon4)
        self.REQUEST.setIconSize(QtCore.QSize(30, 30))
        self.REQUEST.setObjectName("REQUEST")
        self.label36 = QtWidgets.QLabel(self.frame_15)
        self.label36.setGeometry(QtCore.QRect(80, 30, 371, 71))
        self.label36.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label36.setObjectName("label36")
        self.BOOK_TITLE = QtWidgets.QLineEdit(self.frame_15)
        self.BOOK_TITLE.setGeometry(QtCore.QRect(90, 150, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.BOOK_TITLE.setFont(font)
        self.BOOK_TITLE.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.BOOK_TITLE.setMaxLength(100)
        self.BOOK_TITLE.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.BOOK_TITLE.setDragEnabled(True)
        self.BOOK_TITLE.setPlaceholderText("")
        self.BOOK_TITLE.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.BOOK_TITLE.setClearButtonEnabled(True)
        self.BOOK_TITLE.setObjectName("BOOK_TITLE")
        self.AUTHOR = QtWidgets.QLineEdit(self.frame_15)
        self.AUTHOR.setGeometry(QtCore.QRect(90, 220, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.AUTHOR.setFont(font)
        self.AUTHOR.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.AUTHOR.setMaxLength(100)
        self.AUTHOR.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.AUTHOR.setDragEnabled(True)
        self.AUTHOR.setPlaceholderText("")
        self.AUTHOR.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.AUTHOR.setClearButtonEnabled(True)
        self.AUTHOR.setObjectName("AUTHOR")
        self.RELEASE_YEAR = QtWidgets.QLineEdit(self.frame_15)
        self.RELEASE_YEAR.setGeometry(QtCore.QRect(90, 290, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.RELEASE_YEAR.setFont(font)
        self.RELEASE_YEAR.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.RELEASE_YEAR.setMaxLength(4)
        self.RELEASE_YEAR.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.RELEASE_YEAR.setDragEnabled(True)
        self.RELEASE_YEAR.setPlaceholderText("")
        self.RELEASE_YEAR.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.RELEASE_YEAR.setClearButtonEnabled(True)
        self.RELEASE_YEAR.setObjectName("RELEASE_YEAR")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(180, 0, 1121, 131))
        self.frame_14.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_14.raise_()
        self.frame_16.raise_()
        self.frame_15.raise_()
        #RequestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RequestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        #RequestWindow.setMenuBar(self.menubar)

        self.retranslateUi(RequestWindow)
        QtCore.QMetaObject.connectSlotsByName(RequestWindow)

    def retranslateUi(self, RequestWindow):
        _translate = QtCore.QCoreApplication.translate
        RequestWindow.setWindowTitle(_translate("RequestWindow", "Request a Book"))
        self.label19.setText(_translate("RequestWindow", "Library"))
        self.log_credits_24.setText(_translate("RequestWindow", "My account"))
        self.log_credits_25.setText(_translate("RequestWindow", "Books"))
        self.MY_ACCOUNT.setText(_translate("RequestWindow", "My account"))
        self.BOOKS.setText(_translate("RequestWindow", "Books"))
        self.label38.setText(_translate("RequestWindow", "Book Title"))
        self.label39.setText(_translate("RequestWindow", "Author"))
        self.label40.setText(_translate("RequestWindow", "Release Year"))
        self.REQUEST.setText(_translate("RequestWindow", "Request"))
        self.label36.setText(_translate("RequestWindow", "Request adding a book"))
