# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Agent_books.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BooksWindow(object):
    def setupUi(self, BooksWindow):
        BooksWindow.setObjectName("BooksWindow")
        BooksWindow.resize(1179, 723)
        BooksWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.BookWindow = QtWidgets.QWidget(BooksWindow)
        self.BookWindow.setObjectName("BookWindow")
        self.frame_5 = QtWidgets.QFrame(self.BookWindow)
        self.frame_5.setGeometry(QtCore.QRect(0, -10, 1181, 91))
        self.frame_5.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(28, 33, 40);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label20 = QtWidgets.QLabel(self.frame_5)
        self.label20.setGeometry(QtCore.QRect(10, 0, 411, 71))
        self.label20.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label20.setObjectName("label20")
        self.icon = QtWidgets.QPushButton(self.frame_5)
        self.icon.setGeometry(QtCore.QRect(380, 10, 91, 61))
        self.icon.setStyleSheet("background-color: rgba(42, 41, 41, 0);")
        self.icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/milky-way.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon)
        self.icon.setIconSize(QtCore.QSize(50, 50))
        self.icon.setObjectName("icon")
        self.manage_members = QtWidgets.QPushButton(self.frame_5)
        self.manage_members.setGeometry(QtCore.QRect(1010, 20, 151, 61))
        self.manage_members.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manage_members.setIcon(icon1)
        self.manage_members.setIconSize(QtCore.QSize(25, 25))
        self.manage_members.setObjectName("manage_members")
        self.Books_table = QtWidgets.QTableWidget(self.BookWindow)
        self.Books_table.setGeometry(QtCore.QRect(590, 130, 571, 561))
        self.Books_table.setStyleSheet("color:white;\n"
"border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(34, 39, 46);")
        self.Books_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Books_table.setObjectName("Books_table")
        self.Books_table.setColumnCount(5)
        self.Books_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Books_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Books_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Books_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Books_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Books_table.setHorizontalHeaderItem(4, item)
        self.label22 = QtWidgets.QLabel(self.BookWindow)
        self.label22.setGeometry(QtCore.QRect(260, 130, 91, 31))
        self.label22.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label22.setObjectName("label22")
        self.label23 = QtWidgets.QLabel(self.BookWindow)
        self.label23.setGeometry(QtCore.QRect(50, 200, 121, 31))
        self.label23.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23.setObjectName("label23")
        self.add_book = QtWidgets.QPushButton(self.BookWindow)
        self.add_book.setGeometry(QtCore.QRect(260, 230, 191, 31))
        self.add_book.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(36, 31, 49);\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/borrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_book.setIcon(icon2)
        self.add_book.setIconSize(QtCore.QSize(30, 30))
        self.add_book.setObjectName("add_book")
        self.label21 = QtWidgets.QLabel(self.BookWindow)
        self.label21.setGeometry(QtCore.QRect(50, 130, 91, 31))
        self.label21.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label21.setObjectName("label21")
        self.bktitle_in = QtWidgets.QLineEdit(self.BookWindow)
        self.bktitle_in.setGeometry(QtCore.QRect(50, 160, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bktitle_in.setFont(font)
        self.bktitle_in.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.bktitle_in.setMaxLength(100)
        self.bktitle_in.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bktitle_in.setDragEnabled(True)
        self.bktitle_in.setPlaceholderText("")
        self.bktitle_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.bktitle_in.setClearButtonEnabled(True)
        self.bktitle_in.setObjectName("bktitle_in")
        self.bkauthor_in = QtWidgets.QLineEdit(self.BookWindow)
        self.bkauthor_in.setGeometry(QtCore.QRect(260, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bkauthor_in.setFont(font)
        self.bkauthor_in.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.bkauthor_in.setMaxLength(100)
        self.bkauthor_in.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bkauthor_in.setDragEnabled(True)
        self.bkauthor_in.setPlaceholderText("")
        self.bkauthor_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.bkauthor_in.setClearButtonEnabled(True)
        self.bkauthor_in.setObjectName("bkauthor_in")
        self.bkyear_in = QtWidgets.QLineEdit(self.BookWindow)
        self.bkyear_in.setGeometry(QtCore.QRect(50, 230, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bkyear_in.setFont(font)
        self.bkyear_in.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.bkyear_in.setMaxLength(4)
        self.bkyear_in.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bkyear_in.setDragEnabled(True)
        self.bkyear_in.setPlaceholderText("")
        self.bkyear_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.bkyear_in.setClearButtonEnabled(True)
        self.bkyear_in.setObjectName("bkyear_in")
        self.frame_15 = QtWidgets.QFrame(self.BookWindow)
        self.frame_15.setGeometry(QtCore.QRect(10, 90, 551, 211))
        self.frame_15.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label20_2 = QtWidgets.QLabel(self.frame_15)
        self.label20_2.setGeometry(QtCore.QRect(170, -10, 171, 71))
        self.label20_2.setStyleSheet("font: 63 italic 22pt \"URW Bookman\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label20_2.setObjectName("label20_2")
        self.frame_16 = QtWidgets.QFrame(self.BookWindow)
        self.frame_16.setGeometry(QtCore.QRect(10, 310, 551, 241))
        self.frame_16.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.sub_modifications = QtWidgets.QPushButton(self.frame_16)
        self.sub_modifications.setGeometry(QtCore.QRect(290, 110, 181, 41))
        self.sub_modifications.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sub_modifications.setIcon(icon3)
        self.sub_modifications.setIconSize(QtCore.QSize(20, 20))
        self.sub_modifications.setObjectName("sub_modifications")
        self.delete_book = QtWidgets.QPushButton(self.frame_16)
        self.delete_book.setGeometry(QtCore.QRect(290, 170, 181, 41))
        self.delete_book.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_book.setIcon(icon4)
        self.delete_book.setIconSize(QtCore.QSize(20, 20))
        self.delete_book.setObjectName("delete_book")
        self.label21_2 = QtWidgets.QLabel(self.frame_16)
        self.label21_2.setGeometry(QtCore.QRect(40, 10, 91, 31))
        self.label21_2.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label21_2.setObjectName("label21_2")
        self.label22_2 = QtWidgets.QLabel(self.frame_16)
        self.label22_2.setGeometry(QtCore.QRect(40, 150, 91, 31))
        self.label22_2.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label22_2.setObjectName("label22_2")
        self.bktitle_mod = QtWidgets.QLineEdit(self.frame_16)
        self.bktitle_mod.setGeometry(QtCore.QRect(40, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bktitle_mod.setFont(font)
        self.bktitle_mod.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.bktitle_mod.setMaxLength(100)
        self.bktitle_mod.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bktitle_mod.setDragEnabled(True)
        self.bktitle_mod.setPlaceholderText("")
        self.bktitle_mod.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.bktitle_mod.setClearButtonEnabled(True)
        self.bktitle_mod.setObjectName("bktitle_mod")
        self.bkauthor_mod = QtWidgets.QLineEdit(self.frame_16)
        self.bkauthor_mod.setGeometry(QtCore.QRect(40, 180, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bkauthor_mod.setFont(font)
        self.bkauthor_mod.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.bkauthor_mod.setMaxLength(100)
        self.bkauthor_mod.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bkauthor_mod.setDragEnabled(True)
        self.bkauthor_mod.setPlaceholderText("")
        self.bkauthor_mod.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.bkauthor_mod.setClearButtonEnabled(True)
        self.bkauthor_mod.setObjectName("bkauthor_mod")
        self.bkyear_mod = QtWidgets.QLineEdit(self.frame_16)
        self.bkyear_mod.setGeometry(QtCore.QRect(40, 110, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bkyear_mod.setFont(font)
        self.bkyear_mod.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.bkyear_mod.setMaxLength(4)
        self.bkyear_mod.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.bkyear_mod.setDragEnabled(True)
        self.bkyear_mod.setPlaceholderText("")
        self.bkyear_mod.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.bkyear_mod.setClearButtonEnabled(True)
        self.bkyear_mod.setObjectName("bkyear_mod")
        self.label23_2 = QtWidgets.QLabel(self.frame_16)
        self.label23_2.setGeometry(QtCore.QRect(40, 80, 121, 31))
        self.label23_2.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23_2.setObjectName("label23_2")
        self.title_in = QtWidgets.QLineEdit(self.BookWindow)
        self.title_in.setGeometry(QtCore.QRect(590, 90, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.title_in.setFont(font)
        self.title_in.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.title_in.setMaxLength(100)
        self.title_in.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.title_in.setDragEnabled(True)
        self.title_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.title_in.setClearButtonEnabled(True)
        self.title_in.setObjectName("title_in")
        self.search = QtWidgets.QPushButton(self.BookWindow)
        self.search.setGeometry(QtCore.QRect(1070, 90, 91, 31))
        self.search.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(36, 31, 49);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 10px;\n"
"    padding: 0px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Library Management/Windows_Ui/Assets/Ui/Icons/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon5)
        self.search.setIconSize(QtCore.QSize(17, 17))
        self.search.setObjectName("search")
        self.frame_17 = QtWidgets.QFrame(self.BookWindow)
        self.frame_17.setGeometry(QtCore.QRect(10, 560, 321, 131))
        self.frame_17.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label21_3 = QtWidgets.QLabel(self.frame_17)
        self.label21_3.setGeometry(QtCore.QRect(20, 10, 281, 31))
        self.label21_3.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label21_3.setObjectName("label21_3")
        self.books_num = QtWidgets.QLineEdit(self.frame_17)
        self.books_num.setGeometry(QtCore.QRect(40, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.books_num.setFont(font)
        self.books_num.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.books_num.setMaxLength(100)
        self.books_num.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.books_num.setDragEnabled(True)
        self.books_num.setReadOnly(True)
        self.books_num.setPlaceholderText("")
        self.books_num.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.books_num.setClearButtonEnabled(True)
        self.books_num.setObjectName("books_num")
        self.frame_18 = QtWidgets.QFrame(self.BookWindow)
        self.frame_18.setGeometry(QtCore.QRect(340, 560, 221, 131))
        self.frame_18.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label21_4 = QtWidgets.QLabel(self.frame_18)
        self.label21_4.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.label21_4.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label21_4.setObjectName("label21_4")
        self.memb_num = QtWidgets.QLineEdit(self.frame_18)
        self.memb_num.setGeometry(QtCore.QRect(40, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.memb_num.setFont(font)
        self.memb_num.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.memb_num.setMaxLength(100)
        self.memb_num.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.memb_num.setDragEnabled(True)
        self.memb_num.setReadOnly(True)
        self.memb_num.setPlaceholderText("")
        self.memb_num.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.memb_num.setClearButtonEnabled(True)
        self.memb_num.setObjectName("memb_num")
        self.frame_15.raise_()
        self.frame_5.raise_()
        self.Books_table.raise_()
        self.label22.raise_()
        self.label23.raise_()
        self.add_book.raise_()
        self.label21.raise_()
        self.bktitle_in.raise_()
        self.bkauthor_in.raise_()
        self.bkyear_in.raise_()
        self.frame_16.raise_()
        self.title_in.raise_()
        self.search.raise_()
        self.frame_17.raise_()
        self.frame_18.raise_()
        #BooksWindow.setCentralWidget(self.BookWindow)
        self.menubar = QtWidgets.QMenuBar(BooksWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 22))
        self.menubar.setObjectName("menubar")
        #BooksWindow.setMenuBar(self.menubar)

        self.retranslateUi(BooksWindow)
        QtCore.QMetaObject.connectSlotsByName(BooksWindow)

    def retranslateUi(self, BooksWindow):
        _translate = QtCore.QCoreApplication.translate
        BooksWindow.setWindowTitle(_translate("BooksWindow", "Manage Books"))
        self.label20.setText(_translate("BooksWindow", "Library Agent Space"))
        self.manage_members.setText(_translate("BooksWindow", "Manage Members "))
        item = self.Books_table.horizontalHeaderItem(0)
        item.setText(_translate("BooksWindow", "code"))
        item = self.Books_table.horizontalHeaderItem(1)
        item.setText(_translate("BooksWindow", "Title"))
        item = self.Books_table.horizontalHeaderItem(2)
        item.setText(_translate("BooksWindow", "Author"))
        item = self.Books_table.horizontalHeaderItem(3)
        item.setText(_translate("BooksWindow", "Release Date"))
        item = self.Books_table.horizontalHeaderItem(4)
        item.setText(_translate("BooksWindow", "Status"))
        self.label22.setText(_translate("BooksWindow", "Author"))
        self.label23.setText(_translate("BooksWindow", "Release Year"))
        self.add_book.setText(_translate("BooksWindow", "Add Book"))
        self.label21.setText(_translate("BooksWindow", "Book Title"))
        self.label20_2.setText(_translate("BooksWindow", "Add a Book"))
        self.sub_modifications.setText(_translate("BooksWindow", "Submit Modification"))
        self.delete_book.setText(_translate("BooksWindow", "dELETE"))
        self.label21_2.setText(_translate("BooksWindow", "Book Title"))
        self.label22_2.setText(_translate("BooksWindow", "Author"))
        self.label23_2.setText(_translate("BooksWindow", "Release Year"))
        self.title_in.setPlaceholderText(_translate("BooksWindow", "Title..."))
        self.search.setText(_translate("BooksWindow", "Submit"))
        self.label21_3.setText(_translate("BooksWindow", "Number of Books in the library"))
        self.label21_4.setText(_translate("BooksWindow", "Number of Members"))
