# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Agent_members.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MembersWidnow(object):
    def setupUi(self, MembersWidnow):
        MembersWidnow.setObjectName("MembersWidnow")
        MembersWidnow.resize(1179, 723)
        MembersWidnow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.MembersWindow = QtWidgets.QWidget(MembersWidnow)
        self.MembersWindow.setObjectName("MembersWindow")
        self.frame_5 = QtWidgets.QFrame(self.MembersWindow)
        self.frame_5.setGeometry(QtCore.QRect(0, -10, 1181, 91))
        self.frame_5.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(28, 33, 40);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label20 = QtWidgets.QLabel(self.frame_5)
        self.label20.setGeometry(QtCore.QRect(10, 0, 411, 71))
        self.label20.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label20.setObjectName("label20")
        self.icon = QtWidgets.QPushButton(self.frame_5)
        self.icon.setGeometry(QtCore.QRect(380, 10, 91, 61))
        self.icon.setStyleSheet("background-color: rgba(42, 41, 41, 0);")
        self.icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/milky-way.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon)
        self.icon.setIconSize(QtCore.QSize(50, 50))
        self.icon.setObjectName("icon")
        self.manage_books = QtWidgets.QPushButton(self.frame_5)
        self.manage_books.setGeometry(QtCore.QRect(1010, 20, 151, 61))
        self.manage_books.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manage_books.setIcon(icon1)
        self.manage_books.setIconSize(QtCore.QSize(25, 25))
        self.manage_books.setObjectName("manage_books")
        self.Members_table = QtWidgets.QTableWidget(self.MembersWindow)
        self.Members_table.setGeometry(QtCore.QRect(590, 130, 571, 561))
        self.Members_table.setStyleSheet("color:white;\n"
"border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(34, 39, 46);")
        self.Members_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Members_table.setObjectName("Members_table")
        self.Members_table.setColumnCount(5)
        self.Members_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Members_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Members_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Members_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Members_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Members_table.setHorizontalHeaderItem(4, item)
        self.label22 = QtWidgets.QLabel(self.MembersWindow)
        self.label22.setGeometry(QtCore.QRect(310, 180, 101, 31))
        self.label22.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label22.setObjectName("label22")
        self.label23 = QtWidgets.QLabel(self.MembersWindow)
        self.label23.setGeometry(QtCore.QRect(50, 250, 61, 31))
        self.label23.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23.setObjectName("label23")
        self.label21 = QtWidgets.QLabel(self.MembersWindow)
        self.label21.setGeometry(QtCore.QRect(50, 180, 101, 31))
        self.label21.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label21.setObjectName("label21")
        self.fname = QtWidgets.QLineEdit(self.MembersWindow)
        self.fname.setGeometry(QtCore.QRect(50, 210, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.fname.setFont(font)
        self.fname.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.fname.setMaxLength(100)
        self.fname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fname.setDragEnabled(True)
        self.fname.setPlaceholderText("")
        self.fname.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.fname.setClearButtonEnabled(True)
        self.fname.setObjectName("fname")
        self.lname = QtWidgets.QLineEdit(self.MembersWindow)
        self.lname.setGeometry(QtCore.QRect(310, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lname.setFont(font)
        self.lname.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.lname.setMaxLength(100)
        self.lname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lname.setDragEnabled(True)
        self.lname.setPlaceholderText("")
        self.lname.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lname.setClearButtonEnabled(True)
        self.lname.setObjectName("lname")
        self.phone = QtWidgets.QLineEdit(self.MembersWindow)
        self.phone.setGeometry(QtCore.QRect(110, 280, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.phone.setFont(font)
        self.phone.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.phone.setMaxLength(10)
        self.phone.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.phone.setDragEnabled(True)
        self.phone.setPlaceholderText("")
        self.phone.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.phone.setClearButtonEnabled(True)
        self.phone.setObjectName("phone")
        self.frame_15 = QtWidgets.QFrame(self.MembersWindow)
        self.frame_15.setGeometry(QtCore.QRect(10, 90, 551, 601))
        self.frame_15.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label20_2 = QtWidgets.QLabel(self.frame_15)
        self.label20_2.setGeometry(QtCore.QRect(50, -10, 421, 71))
        self.label20_2.setStyleSheet("font: 63 italic 22pt \"URW Bookman\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label20_2.setObjectName("label20_2")
        self.sub_modifications = QtWidgets.QPushButton(self.frame_15)
        self.sub_modifications.setGeometry(QtCore.QRect(180, 440, 181, 41))
        self.sub_modifications.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sub_modifications.setIcon(icon2)
        self.sub_modifications.setIconSize(QtCore.QSize(20, 20))
        self.sub_modifications.setObjectName("sub_modifications")
        self.deletemember = QtWidgets.QPushButton(self.frame_15)
        self.deletemember.setGeometry(QtCore.QRect(180, 380, 181, 41))
        self.deletemember.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletemember.setIcon(icon3)
        self.deletemember.setIconSize(QtCore.QSize(20, 20))
        self.deletemember.setObjectName("deletemember")
        self.addmember = QtWidgets.QPushButton(self.frame_15)
        self.addmember.setGeometry(QtCore.QRect(180, 320, 181, 41))
        self.addmember.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(26, 95, 180);\n"
"    border: 1px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addmember.setIcon(icon4)
        self.addmember.setIconSize(QtCore.QSize(20, 20))
        self.addmember.setObjectName("addmember")
        self.email = QtWidgets.QLineEdit(self.frame_15)
        self.email.setGeometry(QtCore.QRect(300, 190, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.email.setMaxLength(100)
        self.email.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email.setDragEnabled(True)
        self.email.setPlaceholderText("")
        self.email.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        self.label23_2 = QtWidgets.QLabel(self.frame_15)
        self.label23_2.setGeometry(QtCore.QRect(300, 160, 121, 31))
        self.label23_2.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23_2.setObjectName("label23_2")
        self.label23_4 = QtWidgets.QLabel(self.frame_15)
        self.label23_4.setGeometry(QtCore.QRect(170, 230, 121, 31))
        self.label23_4.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23_4.setObjectName("label23_4")
        self.id = QtWidgets.QLineEdit(self.frame_15)
        self.id.setGeometry(QtCore.QRect(170, 260, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.id.setFont(font)
        self.id.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.id.setMaxLength(10)
        self.id.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.id.setDragEnabled(True)
        self.id.setPlaceholderText("")
        self.id.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.id.setClearButtonEnabled(True)
        self.id.setObjectName("id")
        self.delete_book_5 = QtWidgets.QPushButton(self.frame_15)
        self.delete_book_5.setGeometry(QtCore.QRect(40, 180, 61, 51))
        self.delete_book_5.setStyleSheet("font: 75 13pt \"Ubuntu\";")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/algeria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_book_5.setIcon(icon5)
        self.delete_book_5.setIconSize(QtCore.QSize(20, 20))
        self.delete_book_5.setObjectName("delete_book_5")
        self.title_in = QtWidgets.QLineEdit(self.MembersWindow)
        self.title_in.setGeometry(QtCore.QRect(590, 90, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.title_in.setFont(font)
        self.title_in.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 13pt \"Ubuntu Mono\";\n"
"\n"
"\n"
"")
        self.title_in.setMaxLength(100)
        self.title_in.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.title_in.setDragEnabled(True)
        self.title_in.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.title_in.setClearButtonEnabled(True)
        self.title_in.setObjectName("title_in")
        self.search_mem = QtWidgets.QPushButton(self.MembersWindow)
        self.search_mem.setGeometry(QtCore.QRect(1070, 90, 91, 31))
        self.search_mem.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(36, 31, 49);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 10px;\n"
"    padding: 0px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Library Management/Windows_Ui/Assets/Ui/Icons/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_mem.setIcon(icon6)
        self.search_mem.setIconSize(QtCore.QSize(17, 17))
        self.search_mem.setObjectName("search_mem")
        self.frame_15.raise_()
        self.frame_5.raise_()
        self.Members_table.raise_()
        self.label22.raise_()
        self.label23.raise_()
        self.label21.raise_()
        self.fname.raise_()
        self.lname.raise_()
        self.phone.raise_()
        self.title_in.raise_()
        self.search_mem.raise_()
        #MembersWidnow.setCentralWidget(self.MembersWindow)
        self.menubar = QtWidgets.QMenuBar(MembersWidnow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 22))
        self.menubar.setObjectName("menubar")
        #MembersWidnow.setMenuBar(self.menubar)

        self.retranslateUi(MembersWidnow)
        QtCore.QMetaObject.connectSlotsByName(MembersWidnow)

    def retranslateUi(self, MembersWidnow):
        _translate = QtCore.QCoreApplication.translate
        MembersWidnow.setWindowTitle(_translate("MembersWidnow", "Manage Members"))
        self.label20.setText(_translate("MembersWidnow", "Library Agent Space"))
        self.manage_books.setText(_translate("MembersWidnow", "Manage Books"))
        item = self.Members_table.horizontalHeaderItem(0)
        item.setText(_translate("MembersWidnow", "First Name"))
        item = self.Members_table.horizontalHeaderItem(1)
        item.setText(_translate("MembersWidnow", "Last Name"))
        item = self.Members_table.horizontalHeaderItem(2)
        item.setText(_translate("MembersWidnow", "ID"))
        item = self.Members_table.horizontalHeaderItem(3)
        item.setText(_translate("MembersWidnow", "Phone"))
        item = self.Members_table.horizontalHeaderItem(4)
        item.setText(_translate("MembersWidnow", "Email"))
        self.label22.setText(_translate("MembersWidnow", "Last Name"))
        self.label23.setText(_translate("MembersWidnow", "Phone"))
        self.label21.setText(_translate("MembersWidnow", "First Name"))
        self.label20_2.setText(_translate("MembersWidnow", "Manage Member Informations"))
        self.sub_modifications.setText(_translate("MembersWidnow", "Submit Modification"))
        self.deletemember.setText(_translate("MembersWidnow", "dELETE"))
        self.addmember.setText(_translate("MembersWidnow", "Add Member"))
        self.label23_2.setText(_translate("MembersWidnow", "Email"))
        self.label23_4.setText(_translate("MembersWidnow", "ID"))
        self.delete_book_5.setText(_translate("MembersWidnow", "+213"))
        self.title_in.setPlaceholderText(_translate("MembersWidnow", "Enter any Member First or Last Name Or ID"))
        self.search_mem.setText(_translate("MembersWidnow", "Submit"))
