# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 629)
        MainWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 171, 621))
        self.frame_16.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label19 = QtWidgets.QLabel(self.frame_16)
        self.label19.setGeometry(QtCore.QRect(10, 0, 141, 71))
        self.label19.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label19.setObjectName("label19")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 101, 41))
        self.pushButton_14.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.pushButton_14.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.log_credits_24 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_24.setGeometry(QtCore.QRect(920, 20, 181, 41))
        self.log_credits_24.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_24.setIcon(icon1)
        self.log_credits_24.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_24.setObjectName("log_credits_24")
        self.log_credits_25 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_25.setGeometry(QtCore.QRect(920, 70, 181, 41))
        self.log_credits_25.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_25.setIcon(icon2)
        self.log_credits_25.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_25.setObjectName("log_credits_25")
        self.main_accbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_accbtn.setGeometry(QtCore.QRect(10, 180, 151, 51))
        self.main_accbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.main_accbtn.setIcon(icon1)
        self.main_accbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_accbtn.setObjectName("main_accbtn")
        self.main_booksbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_booksbtn.setGeometry(QtCore.QRect(10, 240, 151, 51))
        self.main_booksbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.main_booksbtn.setIcon(icon2)
        self.main_booksbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_booksbtn.setObjectName("main_booksbtn")
        self.main_reqbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_reqbtn.setGeometry(QtCore.QRect(10, 300, 151, 51))
        self.main_reqbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/interview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_reqbtn.setIcon(icon3)
        self.main_reqbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_reqbtn.setObjectName("main_reqbtn")
        self.icon11 = QtWidgets.QPushButton(self.frame_16)
        self.icon11.setGeometry(QtCore.QRect(-20, 50, 191, 111))
        self.icon11.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon11.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/digital-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon11.setIcon(icon4)
        self.icon11.setIconSize(QtCore.QSize(100, 100))
        self.icon11.setObjectName("icon11")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setGeometry(QtCore.QRect(170, 0, 951, 611))
        self.TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabWidget.setObjectName("TabWidget")
        self.bookstab = QtWidgets.QWidget()
        self.bookstab.setObjectName("bookstab")
        self.frame_5 = QtWidgets.QFrame(self.bookstab)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 941, 131))
        self.frame_5.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label20 = QtWidgets.QLabel(self.frame_5)
        self.label20.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.label20.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label20.setObjectName("label20")
        self.icon12 = QtWidgets.QPushButton(self.frame_5)
        self.icon12.setGeometry(QtCore.QRect(140, 0, 111, 51))
        self.icon12.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon12.setText("")
        self.icon12.setIcon(icon)
        self.icon12.setIconSize(QtCore.QSize(25, 25))
        self.icon12.setObjectName("icon12")
        self.mb_titlein = QtWidgets.QTextEdit(self.frame_5)
        self.mb_titlein.setGeometry(QtCore.QRect(10, 80, 291, 31))
        self.mb_titlein.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_titlein.setObjectName("mb_titlein")
        self.mb_submitbtn = QtWidgets.QPushButton(self.frame_5)
        self.mb_submitbtn.setGeometry(QtCore.QRect(310, 80, 91, 31))
        self.mb_submitbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 10px;\n"
"    padding: 0px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mb_submitbtn.setIcon(icon5)
        self.mb_submitbtn.setIconSize(QtCore.QSize(17, 17))
        self.mb_submitbtn.setObjectName("mb_submitbtn")
        self.Bookstable = QtWidgets.QTableWidget(self.bookstab)
        self.Bookstable.setGeometry(QtCore.QRect(410, 140, 531, 401))
        self.Bookstable.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.Bookstable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Bookstable.setObjectName("Bookstable")
        self.Bookstable.setColumnCount(5)
        self.Bookstable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(4, item)
        self.frame_7 = QtWidgets.QFrame(self.bookstab)
        self.frame_7.setGeometry(QtCore.QRect(0, 140, 401, 401))
        self.frame_7.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label21 = QtWidgets.QLabel(self.frame_7)
        self.label21.setGeometry(QtCore.QRect(80, 10, 91, 31))
        self.label21.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label21.setObjectName("label21")
        self.mb_titleout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_titleout.setEnabled(True)
        self.mb_titleout.setGeometry(QtCore.QRect(60, 40, 281, 31))
        self.mb_titleout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_titleout.setReadOnly(True)
        self.mb_titleout.setObjectName("mb_titleout")
        self.label22 = QtWidgets.QLabel(self.frame_7)
        self.label22.setGeometry(QtCore.QRect(80, 80, 91, 31))
        self.label22.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label22.setObjectName("label22")
        self.mb_authorout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_authorout.setEnabled(True)
        self.mb_authorout.setGeometry(QtCore.QRect(60, 110, 281, 31))
        self.mb_authorout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_authorout.setReadOnly(True)
        self.mb_authorout.setObjectName("mb_authorout")
        self.label23 = QtWidgets.QLabel(self.frame_7)
        self.label23.setGeometry(QtCore.QRect(80, 150, 121, 31))
        self.label23.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23.setObjectName("label23")
        self.mb_rdateout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_rdateout.setEnabled(True)
        self.mb_rdateout.setGeometry(QtCore.QRect(60, 180, 281, 31))
        self.mb_rdateout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_rdateout.setReadOnly(True)
        self.mb_rdateout.setObjectName("mb_rdateout")
        self.label24 = QtWidgets.QLabel(self.frame_7)
        self.label24.setGeometry(QtCore.QRect(80, 220, 121, 31))
        self.label24.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label24.setObjectName("label24")
        self.mb_statusout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_statusout.setEnabled(True)
        self.mb_statusout.setGeometry(QtCore.QRect(60, 250, 281, 31))
        self.mb_statusout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_statusout.setReadOnly(True)
        self.mb_statusout.setObjectName("mb_statusout")
        self.mb_borrowbtn = QtWidgets.QPushButton(self.frame_7)
        self.mb_borrowbtn.setGeometry(QtCore.QRect(100, 300, 191, 41))
        self.mb_borrowbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/borrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mb_borrowbtn.setIcon(icon6)
        self.mb_borrowbtn.setIconSize(QtCore.QSize(30, 30))
        self.mb_borrowbtn.setObjectName("mb_borrowbtn")
        self.TabWidget.addTab(self.bookstab, "")
        self.myaccounttab = QtWidgets.QWidget()
        self.myaccounttab.setObjectName("myaccounttab")
        self.frame_8 = QtWidgets.QFrame(self.myaccounttab)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 941, 121))
        self.frame_8.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label25 = QtWidgets.QLabel(self.frame_8)
        self.label25.setGeometry(QtCore.QRect(310, 20, 231, 71))
        self.label25.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label25.setObjectName("label25")
        self.mm_logoutbtn = QtWidgets.QPushButton(self.frame_8)
        self.mm_logoutbtn.setGeometry(QtCore.QRect(810, 10, 121, 41))
        self.mm_logoutbtn.setStyleSheet("\n"
"QPushButton {\n"
"background-color:rgb(224, 27, 36);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/logout (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mm_logoutbtn.setIcon(icon7)
        self.mm_logoutbtn.setIconSize(QtCore.QSize(20, 20))
        self.mm_logoutbtn.setObjectName("mm_logoutbtn")
        self.frame_10 = QtWidgets.QFrame(self.myaccounttab)
        self.frame_10.setGeometry(QtCore.QRect(10, 130, 391, 441))
        self.frame_10.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label29 = QtWidgets.QLabel(self.frame_10)
        self.label29.setGeometry(QtCore.QRect(40, 200, 181, 31))
        self.label29.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label29.setObjectName("label29")
        self.mm_conpassin = QtWidgets.QTextEdit(self.frame_10)
        self.mm_conpassin.setGeometry(QtCore.QRect(40, 230, 311, 31))
        self.mm_conpassin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_conpassin.setObjectName("mm_conpassin")
        self.label26 = QtWidgets.QLabel(self.frame_10)
        self.label26.setGeometry(QtCore.QRect(60, 10, 271, 71))
        self.label26.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label26.setObjectName("label26")
        self.mm_newpassin = QtWidgets.QTextEdit(self.frame_10)
        self.mm_newpassin.setGeometry(QtCore.QRect(40, 170, 311, 31))
        self.mm_newpassin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_newpassin.setObjectName("mm_newpassin")
        self.label28 = QtWidgets.QLabel(self.frame_10)
        self.label28.setGeometry(QtCore.QRect(40, 140, 151, 31))
        self.label28.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label28.setObjectName("label28")
        self.mm_submitbtn = QtWidgets.QPushButton(self.frame_10)
        self.mm_submitbtn.setGeometry(QtCore.QRect(80, 270, 191, 41))
        self.mm_submitbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.mm_submitbtn.setIconSize(QtCore.QSize(30, 30))
        self.mm_submitbtn.setObjectName("mm_submitbtn")
        self.mm_curpassin = QtWidgets.QTextEdit(self.frame_10)
        self.mm_curpassin.setGeometry(QtCore.QRect(40, 110, 311, 31))
        self.mm_curpassin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_curpassin.setObjectName("mm_curpassin")
        self.label27 = QtWidgets.QLabel(self.frame_10)
        self.label27.setGeometry(QtCore.QRect(40, 80, 161, 31))
        self.label27.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label27.setObjectName("label27")
        self.frame_9 = QtWidgets.QFrame(self.myaccounttab)
        self.frame_9.setGeometry(QtCore.QRect(410, 130, 531, 441))
        self.frame_9.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label32 = QtWidgets.QLabel(self.frame_9)
        self.label32.setGeometry(QtCore.QRect(240, 80, 91, 31))
        self.label32.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label32.setObjectName("label32")
        self.mm_nameout = QtWidgets.QTextEdit(self.frame_9)
        self.mm_nameout.setGeometry(QtCore.QRect(240, 110, 271, 31))
        self.mm_nameout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_nameout.setReadOnly(True)
        self.mm_nameout.setObjectName("mm_nameout")
        self.label33 = QtWidgets.QLabel(self.frame_9)
        self.label33.setGeometry(QtCore.QRect(30, 150, 21, 31))
        self.label33.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label33.setObjectName("label33")
        self.label34 = QtWidgets.QLabel(self.frame_9)
        self.label34.setGeometry(QtCore.QRect(240, 150, 121, 31))
        self.label34.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label34.setObjectName("label34")
        self.label35 = QtWidgets.QLabel(self.frame_9)
        self.label35.setGeometry(QtCore.QRect(30, 220, 121, 31))
        self.label35.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label35.setObjectName("label35")
        self.label30 = QtWidgets.QLabel(self.frame_9)
        self.label30.setGeometry(QtCore.QRect(60, 10, 271, 71))
        self.label30.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label30.setObjectName("label30")
        self.mm_idout = QtWidgets.QTextEdit(self.frame_9)
        self.mm_idout.setGeometry(QtCore.QRect(30, 180, 181, 31))
        self.mm_idout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_idout.setReadOnly(True)
        self.mm_idout.setObjectName("mm_idout")
        self.mm_phoneout = QtWidgets.QTextEdit(self.frame_9)
        self.mm_phoneout.setGeometry(QtCore.QRect(300, 180, 141, 31))
        self.mm_phoneout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_phoneout.setReadOnly(True)
        self.mm_phoneout.setObjectName("mm_phoneout")
        self.mm_fnameout = QtWidgets.QTextEdit(self.frame_9)
        self.mm_fnameout.setGeometry(QtCore.QRect(30, 110, 181, 31))
        self.mm_fnameout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_fnameout.setReadOnly(True)
        self.mm_fnameout.setObjectName("mm_fnameout")
        self.label31 = QtWidgets.QLabel(self.frame_9)
        self.label31.setGeometry(QtCore.QRect(30, 80, 151, 31))
        self.label31.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label31.setObjectName("label31")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_11.setGeometry(QtCore.QRect(240, 180, 61, 31))
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Assets/Ui/Icons/algeria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon8)
        self.pushButton_11.setObjectName("pushButton_11")
        self.mm_mailout = QtWidgets.QTextEdit(self.frame_9)
        self.mm_mailout.setGeometry(QtCore.QRect(30, 250, 261, 31))
        self.mm_mailout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:black;\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mm_mailout.setReadOnly(True)
        self.mm_mailout.setObjectName("mm_mailout")
        self.icon13 = QtWidgets.QPushButton(self.frame_9)
        self.icon13.setGeometry(QtCore.QRect(310, 10, 111, 51))
        self.icon13.setStyleSheet("")
        self.icon13.setText("")
        self.icon13.setIcon(icon1)
        self.icon13.setIconSize(QtCore.QSize(50, 50))
        self.icon13.setObjectName("icon13")
        self.TabWidget.addTab(self.myaccounttab, "")
        self.requesttab = QtWidgets.QWidget()
        self.requesttab.setObjectName("requesttab")
        self.frame_14 = QtWidgets.QFrame(self.requesttab)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 1121, 131))
        self.frame_14.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_15 = QtWidgets.QFrame(self.requesttab)
        self.frame_15.setGeometry(QtCore.QRect(210, 20, 511, 491))
        self.frame_15.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label38 = QtWidgets.QLabel(self.frame_15)
        self.label38.setGeometry(QtCore.QRect(70, 180, 91, 31))
        self.label38.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label38.setObjectName("label38")
        self.mr_btitlein = QtWidgets.QTextEdit(self.frame_15)
        self.mr_btitlein.setGeometry(QtCore.QRect(70, 210, 331, 31))
        self.mr_btitlein.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_btitlein.setObjectName("mr_btitlein")
        self.label39 = QtWidgets.QLabel(self.frame_15)
        self.label39.setGeometry(QtCore.QRect(70, 250, 91, 31))
        self.label39.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label39.setObjectName("label39")
        self.mr_authorin = QtWidgets.QTextEdit(self.frame_15)
        self.mr_authorin.setGeometry(QtCore.QRect(70, 280, 331, 31))
        self.mr_authorin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_authorin.setObjectName("mr_authorin")
        self.label40 = QtWidgets.QLabel(self.frame_15)
        self.label40.setGeometry(QtCore.QRect(70, 320, 121, 31))
        self.label40.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label40.setObjectName("label40")
        self.mr_rdatein = QtWidgets.QTextEdit(self.frame_15)
        self.mr_rdatein.setGeometry(QtCore.QRect(70, 350, 331, 31))
        self.mr_rdatein.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_rdatein.setObjectName("mr_rdatein")
        self.mr_reqbtn = QtWidgets.QPushButton(self.frame_15)
        self.mr_reqbtn.setGeometry(QtCore.QRect(110, 400, 261, 41))
        self.mr_reqbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.mr_reqbtn.setIcon(icon3)
        self.mr_reqbtn.setIconSize(QtCore.QSize(30, 30))
        self.mr_reqbtn.setObjectName("mr_reqbtn")
        self.mr_idin = QtWidgets.QTextEdit(self.frame_15)
        self.mr_idin.setGeometry(QtCore.QRect(70, 150, 331, 31))
        self.mr_idin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_idin.setObjectName("mr_idin")
        self.label37 = QtWidgets.QLabel(self.frame_15)
        self.label37.setGeometry(QtCore.QRect(70, 120, 41, 21))
        self.label37.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label37.setObjectName("label37")
        self.label36 = QtWidgets.QLabel(self.frame_15)
        self.label36.setGeometry(QtCore.QRect(60, 30, 371, 71))
        self.label36.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label36.setObjectName("label36")
        self.TabWidget.addTab(self.requesttab, "")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label19.setText(_translate("MainWindow", "Library"))
        self.log_credits_24.setText(_translate("MainWindow", "My account"))
        self.log_credits_25.setText(_translate("MainWindow", "Books"))
        self.main_accbtn.setText(_translate("MainWindow", "My account"))
        self.main_booksbtn.setText(_translate("MainWindow", "Books"))
        self.main_reqbtn.setText(_translate("MainWindow", "Request"))
        self.label20.setText(_translate("MainWindow", "Catalogue"))
        self.mb_titlein.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mb_titlein.setPlaceholderText(_translate("MainWindow", "Title"))
        self.mb_submitbtn.setText(_translate("MainWindow", "Submit"))
        item = self.Bookstable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "code"))
        item = self.Bookstable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.Bookstable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.Bookstable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Release Date"))
        item = self.Bookstable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.label21.setText(_translate("MainWindow", "Book Title"))
        self.mb_titleout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label22.setText(_translate("MainWindow", "Author"))
        self.mb_authorout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label23.setText(_translate("MainWindow", "Release Date"))
        self.mb_rdateout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label24.setText(_translate("MainWindow", "Status"))
        self.mb_statusout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mb_borrowbtn.setText(_translate("MainWindow", "Borrow"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.bookstab), _translate("MainWindow", "Books"))
        self.label25.setText(_translate("MainWindow", "My Account"))
        self.mm_logoutbtn.setText(_translate("MainWindow", "Logout"))
        self.label29.setText(_translate("MainWindow", "Confirme password"))
        self.mm_conpassin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label26.setText(_translate("MainWindow", "Change password"))
        self.mm_newpassin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label28.setText(_translate("MainWindow", "New password"))
        self.mm_submitbtn.setText(_translate("MainWindow", "Submit"))
        self.mm_curpassin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label27.setText(_translate("MainWindow", "Current password"))
        self.label32.setText(_translate("MainWindow", "Name"))
        self.mm_nameout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label33.setText(_translate("MainWindow", "ID"))
        self.label34.setText(_translate("MainWindow", "Phone"))
        self.label35.setText(_translate("MainWindow", "Mail address"))
        self.label30.setText(_translate("MainWindow", "My Informations"))
        self.mm_idout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mm_phoneout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mm_fnameout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label31.setText(_translate("MainWindow", "Family name"))
        self.pushButton_11.setText(_translate("MainWindow", "+213"))
        self.mm_mailout.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.myaccounttab), _translate("MainWindow", "My account"))
        self.label38.setText(_translate("MainWindow", "Book Title"))
        self.mr_btitlein.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label39.setText(_translate("MainWindow", "Author"))
        self.mr_authorin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label40.setText(_translate("MainWindow", "Release Date"))
        self.mr_rdatein.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mr_reqbtn.setText(_translate("MainWindow", "Request"))
        self.mr_idin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label37.setText(_translate("MainWindow", "ID"))
        self.label36.setText(_translate("MainWindow", "Request adding a book"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.requesttab), _translate("MainWindow", "Request"))
