# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'books.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BooksWindow(object):
    def setupUi(self, BooksWindow):
        BooksWindow.setObjectName("BooksWindow")
        BooksWindow.resize(1128, 629)
        BooksWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.BookWindow = QtWidgets.QWidget(BooksWindow)
        self.BookWindow.setObjectName("BookWindow")
        self.frame_16 = QtWidgets.QFrame(self.BookWindow)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 171, 621))
        self.frame_16.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label19 = QtWidgets.QLabel(self.frame_16)
        self.label19.setGeometry(QtCore.QRect(10, 0, 141, 71))
        self.label19.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label19.setObjectName("label19")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 101, 41))
        self.pushButton_14.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.pushButton_14.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.log_credits_24 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_24.setGeometry(QtCore.QRect(920, 20, 181, 41))
        self.log_credits_24.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_24.setIcon(icon1)
        self.log_credits_24.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_24.setObjectName("log_credits_24")
        self.log_credits_25 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_25.setGeometry(QtCore.QRect(920, 70, 181, 41))
        self.log_credits_25.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_25.setIcon(icon2)
        self.log_credits_25.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_25.setObjectName("log_credits_25")
        self.main_accbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_accbtn.setGeometry(QtCore.QRect(10, 180, 151, 51))
        self.main_accbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.main_accbtn.setIcon(icon1)
        self.main_accbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_accbtn.setObjectName("main_accbtn")
        self.main_booksbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_booksbtn.setGeometry(QtCore.QRect(10, 240, 151, 51))
        self.main_booksbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.main_booksbtn.setIcon(icon2)
        self.main_booksbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_booksbtn.setObjectName("main_booksbtn")
        self.main_reqbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_reqbtn.setGeometry(QtCore.QRect(10, 300, 151, 51))
        self.main_reqbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/interview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_reqbtn.setIcon(icon3)
        self.main_reqbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_reqbtn.setObjectName("main_reqbtn")
        self.icon11 = QtWidgets.QPushButton(self.frame_16)
        self.icon11.setGeometry(QtCore.QRect(-20, 50, 191, 111))
        self.icon11.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon11.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/digital-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon11.setIcon(icon4)
        self.icon11.setIconSize(QtCore.QSize(100, 100))
        self.icon11.setObjectName("icon11")
        self.frame_7 = QtWidgets.QFrame(self.BookWindow)
        self.frame_7.setGeometry(QtCore.QRect(180, 140, 401, 461))
        self.frame_7.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label21 = QtWidgets.QLabel(self.frame_7)
        self.label21.setGeometry(QtCore.QRect(80, 10, 91, 31))
        self.label21.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label21.setObjectName("label21")
        self.mb_titleout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_titleout.setEnabled(True)
        self.mb_titleout.setGeometry(QtCore.QRect(60, 40, 281, 31))
        self.mb_titleout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_titleout.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_titleout.setReadOnly(True)
        self.mb_titleout.setObjectName("mb_titleout")
        self.label22 = QtWidgets.QLabel(self.frame_7)
        self.label22.setGeometry(QtCore.QRect(80, 80, 91, 31))
        self.label22.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(42, 41, 41, 0);")
        self.label22.setObjectName("label22")
        self.mb_authorout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_authorout.setEnabled(True)
        self.mb_authorout.setGeometry(QtCore.QRect(60, 110, 281, 31))
        self.mb_authorout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_authorout.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_authorout.setReadOnly(True)
        self.mb_authorout.setObjectName("mb_authorout")
        self.label23 = QtWidgets.QLabel(self.frame_7)
        self.label23.setGeometry(QtCore.QRect(80, 150, 121, 31))
        self.label23.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label23.setObjectName("label23")
        self.mb_rdateout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_rdateout.setEnabled(True)
        self.mb_rdateout.setGeometry(QtCore.QRect(60, 180, 281, 31))
        self.mb_rdateout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_rdateout.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_rdateout.setReadOnly(True)
        self.mb_rdateout.setObjectName("mb_rdateout")
        self.label24 = QtWidgets.QLabel(self.frame_7)
        self.label24.setGeometry(QtCore.QRect(80, 220, 121, 31))
        self.label24.setStyleSheet("font: 75 16pt \"Ubuntu\";\n"
"background-color: rgba(65, 191, 64, 0);")
        self.label24.setObjectName("label24")
        self.mb_statusout = QtWidgets.QTextEdit(self.frame_7)
        self.mb_statusout.setEnabled(True)
        self.mb_statusout.setGeometry(QtCore.QRect(60, 250, 281, 31))
        self.mb_statusout.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_statusout.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_statusout.setReadOnly(True)
        self.mb_statusout.setObjectName("mb_statusout")
        self.mb_borrowbtn = QtWidgets.QPushButton(self.frame_7)
        self.mb_borrowbtn.setGeometry(QtCore.QRect(100, 300, 191, 41))
        self.mb_borrowbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/borrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mb_borrowbtn.setIcon(icon5)
        self.mb_borrowbtn.setIconSize(QtCore.QSize(30, 30))
        self.mb_borrowbtn.setObjectName("mb_borrowbtn")
        self.Bookstable = QtWidgets.QTableWidget(self.BookWindow)
        self.Bookstable.setGeometry(QtCore.QRect(590, 140, 531, 461))
        self.Bookstable.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.Bookstable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Bookstable.setObjectName("Bookstable")
        self.Bookstable.setColumnCount(5)
        self.Bookstable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Bookstable.setHorizontalHeaderItem(4, item)
        self.frame_5 = QtWidgets.QFrame(self.BookWindow)
        self.frame_5.setGeometry(QtCore.QRect(180, 0, 941, 131))
        self.frame_5.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label20 = QtWidgets.QLabel(self.frame_5)
        self.label20.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.label20.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label20.setObjectName("label20")
        self.icon12 = QtWidgets.QPushButton(self.frame_5)
        self.icon12.setGeometry(QtCore.QRect(140, 0, 111, 51))
        self.icon12.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon12.setText("")
        self.icon12.setIcon(icon)
        self.icon12.setIconSize(QtCore.QSize(25, 25))
        self.icon12.setObjectName("icon12")
        self.mb_titlein = QtWidgets.QTextEdit(self.frame_5)
        self.mb_titlein.setGeometry(QtCore.QRect(10, 80, 291, 31))
        self.mb_titlein.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mb_titlein.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_titlein.setObjectName("mb_titlein")
        self.mb_submitbtn = QtWidgets.QPushButton(self.frame_5)
        self.mb_submitbtn.setGeometry(QtCore.QRect(310, 80, 91, 31))
        self.mb_submitbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 10px;\n"
"    padding: 0px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mb_submitbtn.setIcon(icon6)
        self.mb_submitbtn.setIconSize(QtCore.QSize(17, 17))
        self.mb_submitbtn.setObjectName("mb_submitbtn")
        #BooksWindow.setCentralWidget(self.BookWindow)
        self.menubar = QtWidgets.QMenuBar(BooksWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        #BooksWindow.setMenuBar(self.menubar)

        self.retranslateUi(BooksWindow)
        QtCore.QMetaObject.connectSlotsByName(BooksWindow)

    def retranslateUi(self, BooksWindow):
        _translate = QtCore.QCoreApplication.translate
        BooksWindow.setWindowTitle(_translate("BooksWindow", "Catalogue"))
        self.label19.setText(_translate("BooksWindow", "Library"))
        self.log_credits_24.setText(_translate("BooksWindow", "My account"))
        self.log_credits_25.setText(_translate("BooksWindow", "Books"))
        self.main_accbtn.setText(_translate("BooksWindow", "My account"))
        self.main_booksbtn.setText(_translate("BooksWindow", "Books"))
        self.main_reqbtn.setText(_translate("BooksWindow", "Request"))
        self.label21.setText(_translate("BooksWindow", "Book Title"))
        self.mb_titleout.setHtml(_translate("BooksWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label22.setText(_translate("BooksWindow", "Author"))
        self.mb_authorout.setHtml(_translate("BooksWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label23.setText(_translate("BooksWindow", "Release Date"))
        self.mb_rdateout.setHtml(_translate("BooksWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label24.setText(_translate("BooksWindow", "Status"))
        self.mb_statusout.setHtml(_translate("BooksWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mb_borrowbtn.setText(_translate("BooksWindow", "Borrow"))
        item = self.Bookstable.horizontalHeaderItem(0)
        item.setText(_translate("BooksWindow", "code"))
        item = self.Bookstable.horizontalHeaderItem(1)
        item.setText(_translate("BooksWindow", "Title"))
        item = self.Bookstable.horizontalHeaderItem(2)
        item.setText(_translate("BooksWindow", "Author"))
        item = self.Bookstable.horizontalHeaderItem(3)
        item.setText(_translate("BooksWindow", "Release Date"))
        item = self.Bookstable.horizontalHeaderItem(4)
        item.setText(_translate("BooksWindow", "Status"))
        self.label20.setText(_translate("BooksWindow", "Catalogue"))
        self.mb_titlein.setHtml(_translate("BooksWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mb_titlein.setPlaceholderText(_translate("BooksWindow", "Title"))
        self.mb_submitbtn.setText(_translate("BooksWindow", "Submit"))
