# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Request.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RequestWindow(object):
    def setupUi(self, RequestWindow):
        RequestWindow.setObjectName("RequestWindow")
        RequestWindow.resize(1128, 629)
        RequestWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(RequestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 171, 621))
        self.frame_16.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label19 = QtWidgets.QLabel(self.frame_16)
        self.label19.setGeometry(QtCore.QRect(10, 0, 141, 71))
        self.label19.setStyleSheet("font: 63 italic 30pt \"URW Bookman\";\n"
"color:white;\n"
"background-color: rgba(28, 113, 216, 0);")
        self.label19.setObjectName("label19")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 10, 101, 41))
        self.pushButton_14.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.pushButton_14.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.log_credits_24 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_24.setGeometry(QtCore.QRect(920, 20, 181, 41))
        self.log_credits_24.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/programmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_24.setIcon(icon1)
        self.log_credits_24.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_24.setObjectName("log_credits_24")
        self.log_credits_25 = QtWidgets.QPushButton(self.frame_16)
        self.log_credits_25.setGeometry(QtCore.QRect(920, 70, 181, 41))
        self.log_credits_25.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_credits_25.setIcon(icon2)
        self.log_credits_25.setIconSize(QtCore.QSize(25, 25))
        self.log_credits_25.setObjectName("log_credits_25")
        self.main_accbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_accbtn.setGeometry(QtCore.QRect(10, 180, 151, 51))
        self.main_accbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.main_accbtn.setIcon(icon1)
        self.main_accbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_accbtn.setObjectName("main_accbtn")
        self.main_booksbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_booksbtn.setGeometry(QtCore.QRect(10, 240, 151, 51))
        self.main_booksbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.main_booksbtn.setIcon(icon2)
        self.main_booksbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_booksbtn.setObjectName("main_booksbtn")
        self.main_reqbtn = QtWidgets.QPushButton(self.frame_16)
        self.main_reqbtn.setGeometry(QtCore.QRect(10, 300, 151, 51))
        self.main_reqbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/interview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_reqbtn.setIcon(icon3)
        self.main_reqbtn.setIconSize(QtCore.QSize(25, 25))
        self.main_reqbtn.setObjectName("main_reqbtn")
        self.icon11 = QtWidgets.QPushButton(self.frame_16)
        self.icon11.setGeometry(QtCore.QRect(-20, 50, 191, 111))
        self.icon11.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon11.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/digital-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon11.setIcon(icon4)
        self.icon11.setIconSize(QtCore.QSize(100, 100))
        self.icon11.setObjectName("icon11")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setGeometry(QtCore.QRect(390, 20, 511, 491))
        self.frame_15.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label38 = QtWidgets.QLabel(self.frame_15)
        self.label38.setGeometry(QtCore.QRect(70, 180, 91, 31))
        self.label38.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label38.setObjectName("label38")
        self.mr_btitlein = QtWidgets.QTextEdit(self.frame_15)
        self.mr_btitlein.setGeometry(QtCore.QRect(70, 210, 331, 31))
        self.mr_btitlein.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_btitlein.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mr_btitlein.setObjectName("mr_btitlein")
        self.label39 = QtWidgets.QLabel(self.frame_15)
        self.label39.setGeometry(QtCore.QRect(70, 250, 91, 31))
        self.label39.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label39.setObjectName("label39")
        self.mr_authorin = QtWidgets.QTextEdit(self.frame_15)
        self.mr_authorin.setGeometry(QtCore.QRect(70, 280, 331, 31))
        self.mr_authorin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_authorin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mr_authorin.setObjectName("mr_authorin")
        self.label40 = QtWidgets.QLabel(self.frame_15)
        self.label40.setGeometry(QtCore.QRect(70, 320, 121, 31))
        self.label40.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label40.setObjectName("label40")
        self.mr_rdatein = QtWidgets.QTextEdit(self.frame_15)
        self.mr_rdatein.setGeometry(QtCore.QRect(70, 350, 331, 31))
        self.mr_rdatein.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_rdatein.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mr_rdatein.setObjectName("mr_rdatein")
        self.mr_reqbtn = QtWidgets.QPushButton(self.frame_15)
        self.mr_reqbtn.setGeometry(QtCore.QRect(110, 400, 261, 41))
        self.mr_reqbtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(46, 194, 126);\n"
"    border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.mr_reqbtn.setIcon(icon3)
        self.mr_reqbtn.setIconSize(QtCore.QSize(30, 30))
        self.mr_reqbtn.setObjectName("mr_reqbtn")
        self.mr_idin = QtWidgets.QTextEdit(self.frame_15)
        self.mr_idin.setGeometry(QtCore.QRect(70, 150, 331, 31))
        self.mr_idin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.mr_idin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mr_idin.setObjectName("mr_idin")
        self.label37 = QtWidgets.QLabel(self.frame_15)
        self.label37.setGeometry(QtCore.QRect(70, 120, 41, 21))
        self.label37.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label37.setObjectName("label37")
        self.label36 = QtWidgets.QLabel(self.frame_15)
        self.label36.setGeometry(QtCore.QRect(60, 30, 371, 71))
        self.label36.setStyleSheet("font: 25pt \"Ubuntu Mono\";\n"
"color:black;\n"
"background-color: rgba(28, 113, 216, 0)")
        self.label36.setObjectName("label36")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(180, 0, 1121, 131))
        self.frame_14.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color:rgb(28, 113, 216)")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_14.raise_()
        self.frame_16.raise_()
        self.frame_15.raise_()
        #RequestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RequestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        #RequestWindow.setMenuBar(self.menubar)

        self.retranslateUi(RequestWindow)
        QtCore.QMetaObject.connectSlotsByName(RequestWindow)

    def retranslateUi(self, RequestWindow):
        _translate = QtCore.QCoreApplication.translate
        RequestWindow.setWindowTitle(_translate("RequestWindow", "Request a Book"))
        self.label19.setText(_translate("RequestWindow", "Library"))
        self.log_credits_24.setText(_translate("RequestWindow", "My account"))
        self.log_credits_25.setText(_translate("RequestWindow", "Books"))
        self.main_accbtn.setText(_translate("RequestWindow", "My account"))
        self.main_booksbtn.setText(_translate("RequestWindow", "Books"))
        self.main_reqbtn.setText(_translate("RequestWindow", "Request"))
        self.label38.setText(_translate("RequestWindow", "Book Title"))
        self.mr_btitlein.setHtml(_translate("RequestWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label39.setText(_translate("RequestWindow", "Author"))
        self.mr_authorin.setHtml(_translate("RequestWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label40.setText(_translate("RequestWindow", "Release Date"))
        self.mr_rdatein.setHtml(_translate("RequestWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.mr_reqbtn.setText(_translate("RequestWindow", "Request"))
        self.mr_idin.setHtml(_translate("RequestWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label37.setText(_translate("RequestWindow", "ID"))
        self.label36.setText(_translate("RequestWindow", "Request adding a book"))
