# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1128, 629)
        LoginWindow.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, -10, 1131, 321))
        self.frame_2.setStyleSheet("border: 1px ;\n"
"border-radius: 20px;\n"
"background-color: rgb(28, 113, 216);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label1 = QtWidgets.QLabel(self.frame_2)
        self.label1.setGeometry(QtCore.QRect(160, 60, 221, 71))
        self.label1.setStyleSheet("font: 63 italic 40pt \"URW Bookman\";\n"
"color:white;")
        self.label1.setObjectName("label1")
        self.lg_helpbtn = QtWidgets.QPushButton(self.frame_2)
        self.lg_helpbtn.setGeometry(QtCore.QRect(170, 270, 171, 41))
        self.lg_helpbtn.setStyleSheet("\n"
"QPushButton {\n"
"    transition: all .5s ease;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    border:3px solid white;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    background-color : transparent;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color:rgb(0, 137, 236);;\n"
"    background-color: white;;\n"
"}\n"
"")
        self.lg_helpbtn.setObjectName("lg_helpbtn")
        self.icon2 = QtWidgets.QPushButton(self.frame_2)
        self.icon2.setGeometry(QtCore.QRect(290, 60, 89, 41))
        self.icon2.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/graduate-cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon2.setIcon(icon)
        self.icon2.setIconSize(QtCore.QSize(50, 50))
        self.icon2.setObjectName("icon2")
        self.icon1 = QtWidgets.QPushButton(self.frame_2)
        self.icon1.setGeometry(QtCore.QRect(160, 130, 191, 111))
        self.icon1.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/online-library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon1.setIcon(icon1)
        self.icon1.setIconSize(QtCore.QSize(100, 100))
        self.icon1.setObjectName("icon1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(670, 10, 381, 521))
        self.frame.setStyleSheet("border: 1px;\n"
"border-radius: 20px;\n"
"background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lg_signupbtn = QtWidgets.QPushButton(self.frame)
        self.lg_signupbtn.setGeometry(QtCore.QRect(200, 400, 81, 41))
        self.lg_signupbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lg_signupbtn.setStyleSheet("QPushButton{background-color:transparent;\n"
"color: rgb(46, 194, 126);\n"
"font: 75 12pt \"Ubuntu\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"font:serif;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(46, 194, 126);\n"
"font: 75 15pt \"Ubuntu\";\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"font:serif;\n"
"}")
        self.lg_signupbtn.setObjectName("lg_signupbtn")
        self.label5 = QtWidgets.QLabel(self.frame)
        self.label5.setGeometry(QtCore.QRect(50, 190, 111, 17))
        self.label5.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label5.setObjectName("label5")
        self.lg_idin = QtWidgets.QTextEdit(self.frame)
        self.lg_idin.setGeometry(QtCore.QRect(40, 210, 281, 31))
        self.lg_idin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.lg_idin.setObjectName("lg_idin")
        self.lg_passin = QtWidgets.QTextEdit(self.frame)
        self.lg_passin.setGeometry(QtCore.QRect(40, 270, 281, 31))
        self.lg_passin.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color:rgb(0, 137, 236);\n"
"border-radius: 10px;\n"
"font: 75 14pt \"Ubuntu Mono\";\n"
"\n"
"")
        self.lg_passin.setPlaceholderText("")
        self.lg_passin.setObjectName("lg_passin")
        self.label6 = QtWidgets.QLabel(self.frame)
        self.label6.setGeometry(QtCore.QRect(50, 250, 111, 20))
        self.label6.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label6.setObjectName("label6")
        self.lg_signinbtn = QtWidgets.QPushButton(self.frame)
        self.lg_signinbtn.setGeometry(QtCore.QRect(60, 350, 261, 41))
        self.lg_signinbtn.setStyleSheet("\n"
"QPushButton {\n"
"    transition: all .5s ease;\n"
"    color: rgb(0, 137, 236);;\n"
"    border-radius: 5px;\n"
"    border:3px solid rgb(0, 137, 236);;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    background-color : transparent;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(0, 137, 236);;\n"
"}\n"
"")
        self.lg_signinbtn.setObjectName("lg_signinbtn")
        self.label7 = QtWidgets.QLabel(self.frame)
        self.label7.setGeometry(QtCore.QRect(70, 410, 131, 21))
        self.label7.setStyleSheet("font: 75 12pt \"Ubuntu\";")
        self.label7.setObjectName("label7")
        self.label4 = QtWidgets.QLabel(self.frame)
        self.label4.setGeometry(QtCore.QRect(280, 20, 91, 41))
        self.label4.setStyleSheet("font: 75 20pt \"Ubuntu\";")
        self.label4.setObjectName("label4")
        self.label3 = QtWidgets.QLabel(self.frame)
        self.label3.setGeometry(QtCore.QRect(190, 20, 91, 41))
        self.label3.setStyleSheet("font: 75 20pt \"Ubuntu\";\n"
"color:rgb(28, 113, 216);")
        self.label3.setObjectName("label3")
        self.label2 = QtWidgets.QLabel(self.frame)
        self.label2.setGeometry(QtCore.QRect(30, 20, 161, 41))
        self.label2.setStyleSheet("font: 75 20pt \"Ubuntu\";")
        self.label2.setObjectName("label2")
        self.icon3 = QtWidgets.QPushButton(self.frame)
        self.icon3.setGeometry(QtCore.QRect(80, 60, 191, 111))
        self.icon3.setStyleSheet("background-color: rgba(28, 113, 216, 0);")
        self.icon3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Windows_Ui/Assets/Ui/Icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon3.setIcon(icon2)
        self.icon3.setIconSize(QtCore.QSize(100, 100))
        self.icon3.setObjectName("icon3")
        # LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        # LoginWindow.setMenuBar(self.menubar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.label1.setText(_translate("LoginWindow", "Library"))
        self.lg_helpbtn.setText(_translate("LoginWindow", "HELP"))
        self.lg_signupbtn.setText(_translate("LoginWindow", "Sign Up"))
        self.label5.setText(_translate("LoginWindow", "STUDENT ID"))
        self.lg_idin.setHtml(_translate("LoginWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.lg_idin.setPlaceholderText(_translate("LoginWindow", "3800...."))
        self.lg_passin.setHtml(_translate("LoginWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt; font-weight:400;\"><br /></p></body></html>"))
        self.label6.setText(_translate("LoginWindow", "Password"))
        self.lg_signinbtn.setText(_translate("LoginWindow", "Sign In"))
        self.label7.setText(_translate("LoginWindow", "Not a member yet?"))
        self.label4.setText(_translate("LoginWindow", "account"))
        self.label3.setText(_translate("LoginWindow", "Library"))
        self.label2.setText(_translate("LoginWindow", "Log into Your"))
